stages:
  - environment
  - build
  - test
  - release

buildDebug:
  image: mysteriumnetwork/mobile-ci:1.0.1
  stage: build
  tags: [docker]
  except:
    refs:
      - tags
    changes:
      - "./fastlane/android_version_code"
  script:
    - bundle exec fastlane buildDebug

testDebug:
  image: mysteriumnetwork/mobile-ci:1.0.1
  stage: test
  tags: [docker]
  except:
    refs:
      - tags
    changes:
      - "./fastlane/android_version_code"
  dependencies:
    - buildDebug
  script:
    - bundle exec fastlane test

publishBetanet:
  image: mysteriumnetwork/mobile-ci:1.0.1
  stage: release
  only:
    refs:
      - v3
  tags: [docker]
  before_script:
    - echo "$FASTLANE_ANDROID_SIGNING_FILE_VALUE" | base64 --decode > "$FASTLANE_ANDROID_SIGNING_FILE_PATH"
    - echo "$FASTLANE_ANDROID_SECRET_JSON_VALUE" | base64 --decode > "$FASTLANE_ANDROID_SECRET_JSON_PATH"
    - echo "$GOOGLE_SERVICES_VALUE" | base64 --decode > "$GOOGLE_SERVICES_PATH"
  after_script:
    - rm -f $GOOGLE_SERVICES_PATH $FASTLANE_ANDROID_SIGNING_FILE_PATH $FASTLANE_ANDROID_SECRET_JSON_PATH
  script:
    - bundle exec fastlane build
    - apt update; apt install -y jq
    - RELEASE_ID=$(curl -s -H "Authorization:token $GITHUB_API_TOKEN" https://api.github.com/repos/mysteriumnetwork/mysterium-vpn-mobile/releases/tags/0.0.0-betanet | jq -r .id)
    - ASSET_ID=$(curl -s -H "Authorization:token $GITHUB_API_TOKEN" https://api.github.com/repos/mysteriumnetwork/mysterium-vpn-mobile/releases/$RELEASE_ID/assets | jq -r .[0].id)
    - curl -v -X DELETE -H "Authorization:token $GITHUB_API_TOKEN" -H "Content-Type:application/octet-stream" https://api.github.com/repos/mysteriumnetwork/mysterium-vpn-mobile/releases/assets/$ASSET_ID
    - curl --data-binary @android/app/build/outputs/apk/release/app-release.apk -H "Authorization:token $GITHUB_API_TOKEN" -H "Content-Type:application/octet-stream" https://uploads.github.com/repos/mysteriumnetwork/mysterium-vpn-mobile/releases/$RELEASE_ID/assets?name=myst.apk
